<a href="https://colab.research.google.com/github/crisromero-dev/mly1101-machine-learning-portafolio/blob/main/1_2_2_guia_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
#Carga inicial controlando delimitadores y codificación estándar

df_clientes = pd.read_csv('ecommerce_customer_data.csv', sep=',',encoding='utf-8')

# Inspección de las dimensiones de la matriz de datos
print(f"Dimensiones del dataset cargado: {df_clientes.shape}")

Dimensiones del dataset cargado: (10000, 14)

In [3]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
df_clientes.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [5]:
df_clientes

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [18]:
salarios_ajustados = df_clientes['EstimatedSalary'] * 1.19 + 2.5

In [23]:
df_clientes['AdjustSalary'] = salarios_ajustados

In [24]:
salarios_ajustados

0       120607.6672
1       133928.1702
2       135581.0683
3       111656.1897
4        94112.5790
           ...
9995    114564.5616
9996    121025.2263
9997     50084.3402
9998    110539.8388
9999     45449.5282
Name: EstimatedSalary, Length: 10000, dtype: float64

In [25]:
segmento_analistas = pd.DataFrame({
    'CustomerId': df_clientes['CustomerId'],
    'SalarioEstimadoAjustado': salarios_ajustados
}).iloc[50:101]  # Filas 50 a 100

segmento_analistas

     CustomerId  SalarioEstimadoAjustado
50     15616550              235692.9004
51     15768193              102847.7383
52     15683553              139206.5461
53     15702298              195211.2186
54     15569590               47620.0644
55     15760861              134960.9831
56     15630053              103660.5083
57     15647091               54282.8625
58     15623944                1957.8009
59     15804771               55665.0832
60     15651280              100568.8883
61     15773469              150531.3358
62     15702014              212772.2747
63     15751208              118286.5484
64     15592461              110482.8973
65     15789484               33034.9484
66     15696061              131415.9969
67     15641582              234043.7032
68     15638424              135254.1515
69     15755648               21664.0700
70     15703793               33767.3934
71     15620344               40407.6053
72     15812518               52604.7245
73     15779052               69530.4039
74     15770811              173221.7560
75     15780961               26644.2200
76     15614049              165604.8516
77     15662085              176373.1616
78     15575185              231147.6597
79     15803136              116981.4159
80     15706021              203984.7554
81     15663706              162387.7461
82     15641732               30965.8121
83     15701164              189492.4951
84     15738751                2272.6154
85     15805254              136466.6425
86     15762418              153088.0865
87     15625759              180727.0265
88     15622897              110971.6898
89     15767954              186584.2184
90     15757535              207306.7118
91     15731511              175090.1274
92     15809248              130443.8383
93     15640635              205028.3259
94     15676966              102321.6393
95     15699461              144323.0582
96     15738721               76870.8475
97     15693683              234761.0947
98     15604348              118580.0976
99     15633059                7778.1742
100    15808582              192601.6557

In [26]:
df_clientes.to_csv('ecommerce_customer_data_ajustado.csv', index=False)

In [27]:
df_clientes.to_excel('ecommerce_customer_data_ajustado.xlsx', index=False)

In [28]:
tamaño_csv = os.path.getsize('ecommerce_customer_data_ajustado.csv')
tamaño_excel = os.path.getsize('ecommerce_customer_data_ajustado.xlsx')
print(f'Tamaño del archivo CSV: {tamaño_csv} bytes')
print(f'Tamaño del archivo Excel: {tamaño_excel} bytes')

Tamaño del archivo CSV: 822439 bytes
Tamaño del archivo Excel: 871249 bytes